// [INTENT] SupportPoint.hpp — POD struct representing a single SLA support point.
// A support point is a user-specified or auto-generated location on the model surface
// where a support pillar will be placed. `head_front_radius` controls how large the
// mushroom-cap tip of the support is; `is_new_island` marks newly detected unsupported
// islands to drive incremental UI display.
//
// [STATE] Immutable value type after construction. All fields are public; no invariant.
// [MEMORY] Stack-allocated trivial struct; cereal serialization via `serialize(Archive&)`.
//          The Eigen ctor accepting `Matrix<float,5,1>` enables bulk loading from
//          libIGL PointSet matrices (used in SupportPointGenerator).
// [CONCURRENCY] No mutable shared state. Safe to read concurrently; writes require external sync.
// [COUPLING] `cereal::serialize` uses positional ordinal order (pos, head_front_radius,
//            is_new_island). Inserting a field before `pos` or reordering silently corrupts
//            all saved project files. Same Cereal ordering hazard as PrintConfig fields.
// [HAZARD] H907 — `operator==` compares `pos` with exact `Vec3f ==` (bit equality on float).
//          Two points constructed from slightly different float arithmetic paths that are
//          geometrically identical will compare not-equal. Any deduplication or cache-lookup
//          using this operator will produce false negatives.

#ifndef SLA_SUPPORTPOINT_HPP
#define SLA_SUPPORTPOINT_HPP

#include <libslic3r/Point.hpp>

namespace Slic3r { namespace sla {

// An enum to keep track of where the current points on the ModelObject came from.
// [STATE] Tracks UI interaction state; drives display refresh and undo/redo boundary.
enum class PointsStatus {
    NoPoints,      // No points were generated so far.
    Generating,    // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated, // Points were autogenerated (i.e. copied from the backend).
    UserModified   // User has done some edits.
};

// [INTENT] One SLA support point: surface location + mushroom radius + island flag.
// `head_front_radius` is serialized and restored from project files; changing its
// interpretation after release silently breaks all user projects (Cereal hazard).
struct SupportPoint
{
    Vec3f pos;               // [STATE] World-space 3D position on model surface (float mm)
    float head_front_radius; // [STATE] Radius of the support head tip in mm
    bool  is_new_island;     // [STATE] True if this point covers a newly detected island

    SupportPoint() : pos(Vec3f::Zero()), head_front_radius(0.f), is_new_island(false) {}

    SupportPoint(float pos_x, float pos_y, float pos_z, float head_radius, bool new_island = false)
        : pos(pos_x, pos_y, pos_z), head_front_radius(head_radius), is_new_island(new_island)
    {}

    SupportPoint(Vec3f position, float head_radius, bool new_island = false)
        : pos(position), head_front_radius(head_radius), is_new_island(new_island)
    {}

    // [COUPLING] Bulk-load constructor for libIGL PointSet rows (Matrix<float,5,1>).
    // Columns: [x, y, z, head_radius, is_new_island(as float)].
    // Used by SupportPointGenerator to transfer auto-generated points back into SupportPoints.
    SupportPoint(Eigen::Matrix<float, 5, 1, Eigen::DontAlign> data)
        : pos(data(0), data(1), data(2)), head_front_radius(data(3)), is_new_island(data(4) != 0.f)
    {}

    // [HAZARD] H907 — float bit-equality for pos comparison. Two geometrically coincident
    // points constructed via different arithmetic paths will compare not-equal.
    bool operator==(const SupportPoint& sp) const
    {
        float rdiff = std::abs(head_front_radius - sp.head_front_radius);
        return (pos == sp.pos) && rdiff < float(EPSILON) && is_new_island == sp.is_new_island;
    }

    bool operator!=(const SupportPoint& sp) const { return !(sp == (*this)); }

    // [COUPLING] Cereal positional serialization — field order is load/save contract.
    // Never reorder or insert before existing fields without a migration path.
    template<class Archive> void serialize(Archive& ar) { ar(pos, head_front_radius, is_new_island); }
};

using SupportPoints = std::vector<SupportPoint>;

}} // namespace Slic3r::sla

#endif // SUPPORTPOINT_HPP
