// [INTENT] Layer.hpp — defines the Layer, LayerRegion, and SupportLayer data structures.
//
// The Layer hierarchy is the central data model for the slicing pipeline:
//   PrintObject (3D model)
//     └── Layer[] — horizontal cross-sections at each Z height
//           └── LayerRegion[] — per-PrintRegion sub-areas within the layer
//                 ├── slices (SurfaceCollection) — typed 2D surfaces (top/bottom/internal)
//                 ├── fill_surfaces (SurfaceCollection) — surfaces scheduled for infill
//                 ├── perimeters (ExtrusionEntityCollection) — perimeter toolpaths
//                 └── fills (ExtrusionEntityCollection) — infill toolpaths
//
// Data flow through a layer:
//   1. TriangleMeshSlicer → Layer::m_regions[i].slices (raw untyped surfaces)
//   2. detect_surfaces_type() → types slices as stTop/stBottom/stInternal
//   3. make_perimeters() → fills perimeters + thin_fills, updates fill_surfaces
//   4. make_fills() → fills LayerRegion::fills with infill toolpaths
//   5. GCode::process_layer() → emits G-code from perimeters + fills
//
// [MEMORY] LayerRegion objects are heap-allocated by Layer::add_region() and owned by
//   m_regions (vector of raw pointers). Layer::~Layer() deletes them explicitly.
//   No smart pointers — this is a hot path; smart_ptr overhead was deemed unacceptable.
//   Layer objects themselves are owned by PrintObject::m_layers (raw pointer vector).
// [COUPLING] Layer is tightly coupled to PrintObject (via m_object pointer),
//   PrintRegion (via LayerRegion::m_region), Fill system, and GCode pipeline.

#ifndef slic3r_Layer_hpp_
#define slic3r_Layer_hpp_

#include "libslic3r.h"
#include "BoundingBox.hpp"
#include "Flow.hpp"
#include "SurfaceCollection.hpp"
#include "ExtrusionEntityCollection.hpp"
#include "BoundingBox.hpp"
namespace Slic3r {

class ExPolygon;
using ExPolygons = std::vector<ExPolygon>;
class Layer;
using LayerPtrs = std::vector<Layer*>;
class LayerRegion;
using LayerRegionPtrs = std::vector<LayerRegion*>;
class PrintRegion;
class PrintObject;

namespace FillAdaptive {
struct Octree;
};

namespace FillLightning {
class Generator;
};

// [INTENT] LayerRegion — represents one PrintRegion's portion of a single layer.
//   A layer may have multiple LayerRegions when the object has multiple material
//   assignments (multi-colour/multi-material) or different print settings per region.
//   All perimeter and infill toolpaths are ultimately stored here.
//
// [STATE] All public fields are written by different pipeline stages:
//   slices → written by PrintObject::slice_region()
//   raw_slices → backup before surface type classification (for reslicing)
//   thin_fills → written by PerimeterGenerator during make_perimeters()
//   fill_expolygons, fill_surfaces → written by make_perimeters(), read by make_fills()
//   fill_no_overlap_expolygons → BBS extension to avoid infill/perimeter overlap
//   perimeters → written by make_perimeters()
//   fills → written by make_fills()
//   unsupported_bridge_edges → written by process_external_surfaces()
//
// [COUPLING] LayerRegion depends on: Layer, PrintRegion, Flow, Surface, ExtrusionEntity.
// [MEMORY] Owned by its parent Layer (via m_regions raw pointer vector).
//   Constructor/destructor are protected; only Layer::add_region() can create instances.
class LayerRegion
{
public:
    Layer*             layer() { return m_layer; }
    const Layer*       layer() const { return m_layer; }
    const PrintRegion& region() const { return *m_region; }

    const SurfaceCollection& get_slices() const { return slices; }

    // [STATE] slices — primary typed surface collection for this region and layer.
    //   Surface::surface_type distinguishes stTop, stBottom, stInternal, stInternalSolid, etc.
    //   These surfaces drive infill type selection in make_fills().
    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    SurfaceCollection slices;
    // [STATE] raw_slices — untyped backup of slices before classify_surfaces() runs.
    //   Used to restore the original geometry when reslicing (invalidation of downstream steps).
    //   BBS always backs up (layer_needs_raw_backup returns true unconditionally).
    // Backed up slices before they are split into top/bottom/internal.
    // Only backed up for multi-region layers or layers with elephant foot compensation.
    // FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    ExPolygons raw_slices;

    // [STATE] thin_fills — gap-fill extrusions generated by PerimeterGenerator.
    //   Too narrow for a full perimeter loop; emitted as standalone paths.
    //   Not printed directly from thin_fills; copied into fills during make_fills().
    // collection of extrusion paths/loops filling gaps
    // These fills are generated by the perimeter generator.
    // They are not printed on their own, but they are copied to this->fills during infill generation.
    ExtrusionEntityCollection thin_fills;

    // [STATE] fill_expolygons — untyped polygons available for infill after perimeters.
    //   Derived from fill_surfaces by stripping surface types.
    //   Used by overhang detection and infill re-routing.
    // Unspecified fill polygons, used for overhang detection ("ensure vertical wall thickness feature")
    // and for re-starting of infills.
    ExPolygons fill_expolygons;
    // [STATE] fill_surfaces — typed surfaces scheduled for infill pattern generation.
    //   Passed to Fill::make_fills() which creates the actual toolpaths.
    // collection of surfaces for infill generation
    SurfaceCollection fill_surfaces;
    // [STATE] fill_no_overlap_expolygons — BBS: area where infill must not overlap with walls.
    //   Used for the "infill/perimeter overlap" feature.
    // BBS: Unspecified fill polygons, used for interecting when we don't want the infill/perimeter overlap
    ExPolygons fill_no_overlap_expolygons;

    // collection of expolygons representing the bridged areas (thus not
    // needing support material)
    //    Polygons                    bridged;

    // [STATE] unsupported_bridge_edges — polylines of bridge perimeter edges that
    //   are not supported by the layer below. Used by SupportMaterial to decide
    //   if extra support is needed for a bridge.
    // collection of polylines representing the unsupported bridge edges
    Polylines unsupported_bridge_edges;

    // [STATE] perimeters — ordered extrusion paths for all perimeter loops.
    //   Contains ExtrusionEntityCollection sub-objects, one per island.
    //   Consumed by GCode::process_layer() in the G-code generation pass.
    // ordered collection of extrusion paths/loops to build all perimeters
    // (this collection contains only ExtrusionEntityCollection objects)
    ExtrusionEntityCollection perimeters;

    // [STATE] fills — ordered extrusion paths for infill.
    //   Contains ExtrusionEntityCollection sub-objects, one per fill group.
    //   Consumed by GCode::process_layer().
    // ordered collection of extrusion paths to fill surfaces
    // (this collection contains only ExtrusionEntityCollection objects)
    ExtrusionEntityCollection fills;

    Flow flow(FlowRole role) const;
    Flow flow(FlowRole role, double layer_height) const;
    Flow bridging_flow(FlowRole role, bool thick_bridge = false) const;

    void slices_to_fill_surfaces_clipped();
    void prepare_fill_surfaces();
    // BBS
    void   make_perimeters(const SurfaceCollection& slices,
                           const LayerRegionPtrs&   compatible_regions,
                           SurfaceCollection*       fill_surfaces,
                           ExPolygons*              fill_no_overlap);
    void   process_external_surfaces(const Layer* lower_layer, const Polygons* lower_layer_covered);
    double infill_area_threshold() const;
    // Trim surfaces by trimming polygons. Used by the elephant foot compensation at the 1st layer.
    void trim_surfaces(const Polygons& trimming_polygons);
    // Single elephant foot compensation step, used by the elephant foor compensation at the 1st layer.
    // Trim surfaces by trimming polygons (shrunk by an elephant foot compensation step), but don't shrink narrow parts so much that no
    // perimeter would fit.
    void elephant_foot_compensation_step(const float elephant_foot_compensation_perimeter_step, const Polygons& trimming_polygons);

    void export_region_slices_to_svg(const char* path) const;
    void export_region_fill_surfaces_to_svg(const char* path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void export_region_slices_to_svg_debug(const char* name) const;
    void export_region_fill_surfaces_to_svg_debug(const char* name) const;

    // Is there any valid extrusion assigned to this LayerRegion?
    bool has_extrusions() const { return !this->perimeters.entities.empty() || !this->fills.entities.empty(); }
    // BBS
    void simplify_infill_extrusion_entity() { simplify_entity_collection(&fills); }
    void simplify_wall_extrusion_entity() { simplify_entity_collection(&perimeters); }

private:
    void simplify_entity_collection(ExtrusionEntityCollection* entity_collection);
    void simplify_path(ExtrusionPath* path);
    void simplify_multi_path(ExtrusionMultiPath* multipath);
    void simplify_loop(ExtrusionLoop* loop);

protected:
    friend class Layer;
    friend class PrintObject;

    // [INTENT] Protected constructor: LayerRegion can only be created by Layer::add_region().
    //   Factory pattern enforces correct ownership — raw pointer stored in m_regions.
    LayerRegion(Layer* layer, const PrintRegion* region) : m_layer(layer), m_region(region) {}
    ~LayerRegion() {}

private:
    // [STATE] m_layer — back-pointer to owning Layer. Used to access layer Z, PrintObject, etc.
    //   Not owning; the Layer owns the LayerRegion.
    Layer* m_layer;
    // [STATE] m_region — non-owning pointer to the PrintRegion defining this region's config.
    //   PrintRegion is owned by Print::m_regions and outlives all Layer objects.
    const PrintRegion* m_region;
};

// [INTENT] Layer — represents one horizontal slice of a PrintObject at a specific Z height.
//   Contains multiple LayerRegions (one per PrintRegion contributing to this layer).
//   The Layer is the primary unit of work for the slicing → toolpath → G-code pipeline.
//
// Key Z-coordinate fields:
//   slice_z  — unscaled Z used for mesh-plane intersection (may differ from print_z
//               for adaptive layer heights or overlapping meshes).
//   print_z  — unscaled Z output to G-code (actual nozzle height).
//   height   — layer thickness in mm.
//   bottom_z — convenience: print_z - height.
//
// [STATE] lslices — merged 2D islands for this layer (union of all region slices).
//   Used for travel ordering, overhang detection, and G-code island chaining.
// [STATE] loverhangs — regions of this layer that overhang the layer below.
//   Computed by detect_overhangs() in PrintObject; used to select overhang speeds.
// [STATE] sharp_tails, cantilevers — BBS extensions for auto-support detection.
//   sharp_tails: expolygons of sharp overhanging features requiring support.
//   cantilevers: expolygons of cantilever-style unsupported geometry.
// [STATE] curled_lines — BBS extension: lines estimated to curl during printing.
//   Used by travel planner to avoid dragging over curled material.
//
// [MEMORY] Layer owns its m_regions (raw pointer vector, deleted in ~Layer()).
//   Layer objects are owned by PrintObject::m_layers (also raw pointer vector).
//   No RAII; lifecycle management is manual.
// [COUPLING] Layer depends on PrintObject, LayerRegion, Fill system, Extrusion system.
// [CONCURRENCY] make_fills() is called in parallel across layers by PrintObject::infill().
//   Each Layer instance is independent during infill; no cross-layer sharing.
class Layer
{
public:
    // Sequential index of this layer in PrintObject::m_layers, offsetted by the number of raft layers.
    size_t             id() const { return m_id; }
    void               set_id(size_t id) { m_id = id; }
    PrintObject*       object() { return m_object; }
    const PrintObject* object() const { return m_object; }

    // [STATE] Layer doubly-linked list: upper_layer/lower_layer for fast Z-neighbor access.
    //   Not owning; ownership is by PrintObject::m_layers.
    //   Set to nullptr on construction; wired by PrintObject::new_layers().
    Layer*   upper_layer;
    Layer*   lower_layer;
    bool     slicing_errors;
    coordf_t slice_z; // Z used for slicing in unscaled coordinates
    coordf_t print_z; // Z used for printing in unscaled coordinates
    coordf_t height;  // layer height in unscaled coordinates
    coordf_t bottom_z() const { return this->print_z - this->height; }

    // Extrusions estimated to be seriously malformed, estimated during "Estimating curled extrusions" step. These lines should be avoided
    // during fast travels.
    CurledLines curled_lines;

    // BBS
    mutable ExPolygons         sharp_tails;
    mutable ExPolygons         cantilevers;
    mutable std::vector<float> sharp_tails_height;

    // [STATE] lslices — merged ExPolygon islands for this layer.
    //   Produced by Layer::make_slices() which unions all region slices.
    //   Ordered by chain_points() to minimize traversal distance in G-code.
    //   Critical for: travel planning, overhang detection, support material detection.
    //   First-layer lslices are NOT elephant-foot-compensated (by design, per comment).
    // Collection of expolygons generated by slicing the possibly multiple meshes of the source geometry
    // (with possibly differing extruder ID and slicing parameters) and merged.
    // For the first layer, if the Elephant foot compensation is applied, this lslice is uncompensated, therefore
    // it includes the Elephant foot effect, thus it corresponds to the shape of the printed 1st layer.
    // These lslices aka islands are chained by the shortest traverse distance and this traversal
    // order will be applied by the G-code generator to the extrusions fitting into these lslices.
    // These lslices are also used to detect overhangs and overlaps between successive layers, therefore it is important
    // that the 1st lslice is not compensated by the Elephant foot compensation algorithm.
    ExPolygons               lslices;
    ExPolygons               lslices_extrudable; // BBS: the extrudable part of lslices used for tree support
    std::vector<BoundingBox> lslices_bboxes;

    // BBS
    ExPolygons             loverhangs;
    BoundingBox            loverhangs_bbox;
    size_t                 region_count() const { return m_regions.size(); }
    const LayerRegion*     get_region(int idx) const { return m_regions[idx]; }
    LayerRegion*           get_region(int idx) { return m_regions[idx]; }
    LayerRegion*           add_region(const PrintRegion* print_region);
    const LayerRegionPtrs& regions() const { return m_regions; }
    // Test whether whether there are any slices assigned to this layer.
    bool empty() const;
    void make_slices();
    // Backup and restore raw sliced regions if needed.
    // FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    void backup_untyped_slices();
    void restore_untyped_slices();
    // To improve robustness of detect_surfaces_type() when reslicing (working with typed slices), see GH issue #7442.
    void restore_untyped_slices_no_extra_perimeters();
    // Slices merged into islands, to be used by the elephant foot compensation to trim the individual surfaces with the shrunk merged slices.
    ExPolygons             merged(float offset) const;
    template<class T> bool any_internal_region_slice_contains(const T& item) const
    {
        for (const LayerRegion* layerm : m_regions)
            if (layerm->slices.any_internal_contains(item))
                return true;
        return false;
    }
    template<class T> bool any_bottom_region_slice_contains(const T& item) const
    {
        for (const LayerRegion* layerm : m_regions)
            if (layerm->slices.any_bottom_contains(item))
                return true;
        return false;
    }

    // [INTENT] is_perimeter_compatible() — determines if two PrintRegions can share a single
    //   perimeter generation pass. Compatible regions use the same wall filament, wall count,
    //   speeds, and all perimeter-related settings. Grouping compatible regions avoids
    //   redundant perimeter computation and enables correct multi-region perimeter merging.
    // [HAZARD H350] is_perimeter_compatible() uses opt_serialize() for string comparison
    //   of line_width options. This is O(N) string construction + comparison per region pair.
    //   For objects with many regions this is O(N²) in the number of regions per layer.
    // Whether two regions can be printed in a continues perimeter
    static bool is_perimeter_compatible(const PrintRegion& a, const PrintRegion& b);
    void        make_perimeters();
    // Phony version of make_fills() without parameters for Perl integration only.
    void      make_fills() { this->make_fills(nullptr, nullptr); }
    void      make_fills(FillAdaptive::Octree*     adaptive_fill_octree,
                         FillAdaptive::Octree*     support_fill_octree,
                         FillLightning::Generator* lightning_generator = nullptr);
    Polylines generate_sparse_infill_polylines_for_anchoring(FillAdaptive::Octree*     adaptive_fill_octree,
                                                             FillAdaptive::Octree*     support_fill_octree,
                                                             FillLightning::Generator* lightning_generator) const;
    void      make_ironing();

    void export_region_slices_to_svg(const char* path) const;
    void export_region_fill_surfaces_to_svg(const char* path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void export_region_slices_to_svg_debug(const char* name) const;
    void export_region_fill_surfaces_to_svg_debug(const char* name) const;

    // Is there any valid extrusion assigned to this LayerRegion?
    virtual bool has_extrusions() const
    {
        for (auto layerm : m_regions)
            if (layerm->has_extrusions())
                return true;
        return false;
    }

    // BBS
    void simplify_wall_extrusion_path()
    {
        for (auto layerm : m_regions)
            layerm->simplify_wall_extrusion_entity();
    }
    void simplify_infill_extrusion_path()
    {
        for (auto layerm : m_regions)
            layerm->simplify_infill_extrusion_entity();
    }
    // BBS: this function calculate the maximum void grid area of sparse infill of this layer. Just estimated value
    coordf_t get_sparse_infill_max_void_area();

    // [INTENT] idx_higher_or_equal() — template binary/linear search helper used by G-code
    //   processor to find the first layer with Z >= a threshold. Uses binary search on first
    //   call (idx == size_t(-1)), then linear scan for subsequent calls in the same batch.
    //   This hybrid strategy is optimal for the common case of iterating layers in order.
    // FN_HIGHER_EQUAL: the provided object pointer has a Z value >= of an internal threshold.
    // Find the first item with Z value >= of an internal threshold of fn_higher_equal.
    // If no vec item with Z value >= of an internal threshold of fn_higher_equal is found, return vec.size()
    // If the initial idx is size_t(-1), then use binary search.
    // Otherwise search linearly upwards.
    template<typename IteratorType, typename IndexType, typename FN_HIGHER_EQUAL>
    static IndexType idx_higher_or_equal(IteratorType begin, IteratorType end, IndexType idx, FN_HIGHER_EQUAL fn_higher_equal)
    {
        auto size = int(end - begin);
        if (size == 0) {
            idx = 0;
        } else if (idx == IndexType(-1)) {
            // First of the batch of layers per thread pool invocation. Use binary search.
            int idx_low  = 0;
            int idx_high = std::max(0, size - 1);
            while (idx_low + 1 < idx_high) {
                int idx_mid = (idx_low + idx_high) / 2;
                if (fn_higher_equal(begin[idx_mid]))
                    idx_high = idx_mid;
                else
                    idx_low = idx_mid;
            }
            idx = fn_higher_equal(begin[idx_low]) ? idx_low : (fn_higher_equal(begin[idx_high]) ? idx_high : size);
        } else {
            // For the other layers of this batch of layers, search incrementally, which is cheaper than the binary search.
            while (int(idx) < size && !fn_higher_equal(begin[idx]))
                ++idx;
        }
        return idx;
    }

    size_t get_extruder_id(unsigned int filament_id) const;

protected:
    friend class PrintObject;
    friend std::vector<Layer*> new_layers(PrintObject*, const std::vector<coordf_t>&);
    friend std::string         fix_slicing_errors(PrintObject* object, LayerPtrs&, const std::function<void()>&, int&);

    Layer(size_t id, PrintObject* object, coordf_t height, coordf_t print_z, coordf_t slice_z)
        : upper_layer(nullptr)
        , lower_layer(nullptr)
        , slicing_errors(false)
        , slice_z(slice_z)
        , print_z(print_z)
        , height(height)
        , m_id(id)
        , m_object(object)
    {}
    virtual ~Layer();

    // BBS: method to simplify support path
    void simplify_support_entity_collection(ExtrusionEntityCollection* entity_collection);
    void simplify_support_path(ExtrusionPath* path);
    void simplify_support_multi_path(ExtrusionMultiPath* multipath);
    void simplify_support_loop(ExtrusionLoop* loop);

private:
    // Sequential index of layer, 0-based, offsetted by number of raft layers.
    size_t       m_id;
    PrintObject* m_object;
    // [STATE] m_regions — owned collection of LayerRegion pointers.
    //   Each LayerRegion corresponds to one PrintRegion's contribution to this layer.
    //   Allocated by add_region(), deleted by ~Layer().
    LayerRegionPtrs m_regions;
};

enum SupportInnerType { stInnerNormal, stInnerTree };

// [INTENT] SupportLayer — extends Layer with support-specific extrusion data.
//   Support layers may interleave with object layers (e.g. raft under the object).
//   support_fills contains both support base and interface extrusions.
//   For tree supports: base_areas, roof_areas, floor_areas hold the geometry tree.
//
// [STATE] area_groups — BBS tree support: each AreaGroup pairs an ExPolygon with its
//   type (BaseType/RoofType/FloorType/Roof1stLayer), interface_id, distance to top,
//   and flags (need_infill, need_extra_wall). Drives tree support extrusion generation.
// [HAZARD H351] AreaGroup::area is a raw ExPolygon* into one of the ExPolygon vectors
//   (base_areas, roof_areas, etc.). If those vectors are reallocated, all AreaGroup
//   pointers become dangling. Callers must ensure no reallocation occurs between
//   area_groups construction and its consumption.
// [MEMORY] SupportLayer is heap-allocated by PrintObject and owned via raw pointer in
//   PrintObject::m_support_layers. ~SupportLayer is defaulted; no manual cleanup needed
//   beyond the base Layer::~Layer() which handles m_regions.
class SupportLayer : public Layer
{
public:
    // Polygons covered by the supports: base, interface and contact areas.
    // Used to suppress retraction if moving for a support extrusion over these support_islands.
    ExPolygons support_islands;
    // Extrusion paths for the support base and for the support interface and contacts.
    ExtrusionEntityCollection support_fills;
    SupportInnerType          support_type = stInnerNormal;

    // for tree supports
    ExPolygons base_areas;

    // Is there any valid extrusion assigned to this LayerRegion?
    virtual bool has_extrusions() const { return !support_fills.empty(); }

    // Zero based index of an interface layer, used for alternating direction of interface / contact layers.
    size_t interface_id() const { return m_interface_id; }

    void simplify_support_extrusion_path() { this->simplify_support_entity_collection(&support_fills); }

protected:
    friend class PrintObject;
    friend class TreeSupport;

    // The constructor has been made public to be able to insert additional support layers for the skirt or a wipe tower
    // between the raft and the object first layer.
    SupportLayer(size_t id, size_t interface_id, PrintObject* object, coordf_t height, coordf_t print_z, coordf_t slice_z)
        : Layer(id, object, height, print_z, slice_z), m_interface_id(interface_id), support_type(stInnerNormal)
    {}
    virtual ~SupportLayer() = default;

    size_t m_interface_id;

    // for tree support
    ExPolygons roof_areas;
    ExPolygons roof_1st_layer; // the layer just below roof. When working with PolySupport, this layer should be printed with regular material
    ExPolygons floor_areas;
    ExPolygons roof_gap_areas; // the areas in the gap between support roof and overhang
    enum AreaType { BaseType = 0, RoofType = 1, FloorType = 2, Roof1stLayer = 3 };
    struct AreaGroup
    {
        ExPolygon* area;
        int        type;
        int        interface_id = 0;
        coordf_t   dist_to_top; // mm dist to top
        bool       need_infill     = false;
        bool       need_extra_wall = false;
        AreaGroup(ExPolygon* a, int t, coordf_t d) : area(a), type(t), dist_to_top(d) {}
    };
    std::vector<AreaGroup> area_groups;
};

// [INTENT] zs_from_layers() — convenience helper: extracts slice_z floats from a layer container.
//   Used by support material and tree support to build Z-lookup structures.
template<typename LayerContainer> inline std::vector<float> zs_from_layers(const LayerContainer& layers)
{
    std::vector<float> zs;
    zs.reserve(layers.size());
    for (const Layer* l : layers)
        zs.emplace_back((float) l->slice_z);
    return zs;
}

extern BoundingBox get_extents(const LayerRegion& layer_region);
extern BoundingBox get_extents(const LayerRegionPtrs& layer_regions);

}

#endif

class LayerRegion
{
public:
    Layer*             layer() { return m_layer; }
    const Layer*       layer() const { return m_layer; }
    const PrintRegion& region() const { return *m_region; }

    const SurfaceCollection& get_slices() const { return slices; }

    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    SurfaceCollection slices;
    // Backed up slices before they are split into top/bottom/internal.
    // Only backed up for multi-region layers or layers with elephant foot compensation.
    // FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    ExPolygons raw_slices;

    // collection of extrusion paths/loops filling gaps
    // These fills are generated by the perimeter generator.
    // They are not printed on their own, but they are copied to this->fills during infill generation.
    ExtrusionEntityCollection thin_fills;

    // Unspecified fill polygons, used for overhang detection ("ensure vertical wall thickness feature")
    // and for re-starting of infills.
    ExPolygons fill_expolygons;
    // collection of surfaces for infill generation
    SurfaceCollection fill_surfaces;
    // BBS: Unspecified fill polygons, used for interecting when we don't want the infill/perimeter overlap
    ExPolygons fill_no_overlap_expolygons;

    // collection of expolygons representing the bridged areas (thus not
    // needing support material)
    //    Polygons                    bridged;

    // collection of polylines representing the unsupported bridge edges
    Polylines unsupported_bridge_edges;

    // ordered collection of extrusion paths/loops to build all perimeters
    // (this collection contains only ExtrusionEntityCollection objects)
    ExtrusionEntityCollection perimeters;

    // ordered collection of extrusion paths to fill surfaces
    // (this collection contains only ExtrusionEntityCollection objects)
    ExtrusionEntityCollection fills;

    Flow flow(FlowRole role) const;
    Flow flow(FlowRole role, double layer_height) const;
    Flow bridging_flow(FlowRole role, bool thick_bridge = false) const;

    void slices_to_fill_surfaces_clipped();
    void prepare_fill_surfaces();
    // BBS
    void   make_perimeters(const SurfaceCollection& slices,
                           const LayerRegionPtrs&   compatible_regions,
                           SurfaceCollection*       fill_surfaces,
                           ExPolygons*              fill_no_overlap);
    void   process_external_surfaces(const Layer* lower_layer, const Polygons* lower_layer_covered);
    double infill_area_threshold() const;
    // Trim surfaces by trimming polygons. Used by the elephant foot compensation at the 1st layer.
    void trim_surfaces(const Polygons& trimming_polygons);
    // Single elephant foot compensation step, used by the elephant foor compensation at the 1st layer.
    // Trim surfaces by trimming polygons (shrunk by an elephant foot compensation step), but don't shrink narrow parts so much that no
    // perimeter would fit.
    void elephant_foot_compensation_step(const float elephant_foot_compensation_perimeter_step, const Polygons& trimming_polygons);

    void export_region_slices_to_svg(const char* path) const;
    void export_region_fill_surfaces_to_svg(const char* path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void export_region_slices_to_svg_debug(const char* name) const;
    void export_region_fill_surfaces_to_svg_debug(const char* name) const;

    // Is there any valid extrusion assigned to this LayerRegion?
    bool has_extrusions() const { return !this->perimeters.entities.empty() || !this->fills.entities.empty(); }
    // BBS
    void simplify_infill_extrusion_entity() { simplify_entity_collection(&fills); }
    void simplify_wall_extrusion_entity() { simplify_entity_collection(&perimeters); }

private:
    void simplify_entity_collection(ExtrusionEntityCollection* entity_collection);
    void simplify_path(ExtrusionPath* path);
    void simplify_multi_path(ExtrusionMultiPath* multipath);
    void simplify_loop(ExtrusionLoop* loop);

protected:
    friend class Layer;
    friend class PrintObject;

    LayerRegion(Layer* layer, const PrintRegion* region) : m_layer(layer), m_region(region) {}
    ~LayerRegion() {}

private:
    Layer*             m_layer;
    const PrintRegion* m_region;
};

class Layer
{
public:
    // Sequential index of this layer in PrintObject::m_layers, offsetted by the number of raft layers.
    size_t             id() const { return m_id; }
    void               set_id(size_t id) { m_id = id; }
    PrintObject*       object() { return m_object; }
    const PrintObject* object() const { return m_object; }

    Layer*   upper_layer;
    Layer*   lower_layer;
    bool     slicing_errors;
    coordf_t slice_z; // Z used for slicing in unscaled coordinates
    coordf_t print_z; // Z used for printing in unscaled coordinates
    coordf_t height;  // layer height in unscaled coordinates
    coordf_t bottom_z() const { return this->print_z - this->height; }

    // Extrusions estimated to be seriously malformed, estimated during "Estimating curled extrusions" step. These lines should be avoided
    // during fast travels.
    CurledLines curled_lines;

    // BBS
    mutable ExPolygons         sharp_tails;
    mutable ExPolygons         cantilevers;
    mutable std::vector<float> sharp_tails_height;

    // Collection of expolygons generated by slicing the possibly multiple meshes of the source geometry
    // (with possibly differing extruder ID and slicing parameters) and merged.
    // For the first layer, if the Elephant foot compensation is applied, this lslice is uncompensated, therefore
    // it includes the Elephant foot effect, thus it corresponds to the shape of the printed 1st layer.
    // These lslices aka islands are chained by the shortest traverse distance and this traversal
    // order will be applied by the G-code generator to the extrusions fitting into these lslices.
    // These lslices are also used to detect overhangs and overlaps between successive layers, therefore it is important
    // that the 1st lslice is not compensated by the Elephant foot compensation algorithm.
    ExPolygons               lslices;
    ExPolygons               lslices_extrudable; // BBS: the extrudable part of lslices used for tree support
    std::vector<BoundingBox> lslices_bboxes;

    // BBS
    ExPolygons             loverhangs;
    BoundingBox            loverhangs_bbox;
    size_t                 region_count() const { return m_regions.size(); }
    const LayerRegion*     get_region(int idx) const { return m_regions[idx]; }
    LayerRegion*           get_region(int idx) { return m_regions[idx]; }
    LayerRegion*           add_region(const PrintRegion* print_region);
    const LayerRegionPtrs& regions() const { return m_regions; }
    // Test whether whether there are any slices assigned to this layer.
    bool empty() const;
    void make_slices();
    // Backup and restore raw sliced regions if needed.
    // FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    void backup_untyped_slices();
    void restore_untyped_slices();
    // To improve robustness of detect_surfaces_type() when reslicing (working with typed slices), see GH issue #7442.
    void restore_untyped_slices_no_extra_perimeters();
    // Slices merged into islands, to be used by the elephant foot compensation to trim the individual surfaces with the shrunk merged slices.
    ExPolygons             merged(float offset) const;
    template<class T> bool any_internal_region_slice_contains(const T& item) const
    {
        for (const LayerRegion* layerm : m_regions)
            if (layerm->slices.any_internal_contains(item))
                return true;
        return false;
    }
    template<class T> bool any_bottom_region_slice_contains(const T& item) const
    {
        for (const LayerRegion* layerm : m_regions)
            if (layerm->slices.any_bottom_contains(item))
                return true;
        return false;
    }

    // Whether two regions can be printed in a continues perimeter
    static bool is_perimeter_compatible(const PrintRegion& a, const PrintRegion& b);
    void        make_perimeters();
    // Phony version of make_fills() without parameters for Perl integration only.
    void      make_fills() { this->make_fills(nullptr, nullptr); }
    void      make_fills(FillAdaptive::Octree*     adaptive_fill_octree,
                         FillAdaptive::Octree*     support_fill_octree,
                         FillLightning::Generator* lightning_generator = nullptr);
    Polylines generate_sparse_infill_polylines_for_anchoring(FillAdaptive::Octree*     adaptive_fill_octree,
                                                             FillAdaptive::Octree*     support_fill_octree,
                                                             FillLightning::Generator* lightning_generator) const;
    void      make_ironing();

    void export_region_slices_to_svg(const char* path) const;
    void export_region_fill_surfaces_to_svg(const char* path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void export_region_slices_to_svg_debug(const char* name) const;
    void export_region_fill_surfaces_to_svg_debug(const char* name) const;

    // Is there any valid extrusion assigned to this LayerRegion?
    virtual bool has_extrusions() const
    {
        for (auto layerm : m_regions)
            if (layerm->has_extrusions())
                return true;
        return false;
    }

    // BBS
    void simplify_wall_extrusion_path()
    {
        for (auto layerm : m_regions)
            layerm->simplify_wall_extrusion_entity();
    }
    void simplify_infill_extrusion_path()
    {
        for (auto layerm : m_regions)
            layerm->simplify_infill_extrusion_entity();
    }
    // BBS: this function calculate the maximum void grid area of sparse infill of this layer. Just estimated value
    coordf_t get_sparse_infill_max_void_area();

    // FN_HIGHER_EQUAL: the provided object pointer has a Z value >= of an internal threshold.
    // Find the first item with Z value >= of an internal threshold of fn_higher_equal.
    // If no vec item with Z value >= of an internal threshold of fn_higher_equal is found, return vec.size()
    // If the initial idx is size_t(-1), then use binary search.
    // Otherwise search linearly upwards.
    template<typename IteratorType, typename IndexType, typename FN_HIGHER_EQUAL>
    static IndexType idx_higher_or_equal(IteratorType begin, IteratorType end, IndexType idx, FN_HIGHER_EQUAL fn_higher_equal)
    {
        auto size = int(end - begin);
        if (size == 0) {
            idx = 0;
        } else if (idx == IndexType(-1)) {
            // First of the batch of layers per thread pool invocation. Use binary search.
            int idx_low  = 0;
            int idx_high = std::max(0, size - 1);
            while (idx_low + 1 < idx_high) {
                int idx_mid = (idx_low + idx_high) / 2;
                if (fn_higher_equal(begin[idx_mid]))
                    idx_high = idx_mid;
                else
                    idx_low = idx_mid;
            }
            idx = fn_higher_equal(begin[idx_low]) ? idx_low : (fn_higher_equal(begin[idx_high]) ? idx_high : size);
        } else {
            // For the other layers of this batch of layers, search incrementally, which is cheaper than the binary search.
            while (int(idx) < size && !fn_higher_equal(begin[idx]))
                ++idx;
        }
        return idx;
    }

    size_t get_extruder_id(unsigned int filament_id) const;

protected:
    friend class PrintObject;
    friend std::vector<Layer*> new_layers(PrintObject*, const std::vector<coordf_t>&);
    friend std::string         fix_slicing_errors(PrintObject* object, LayerPtrs&, const std::function<void()>&, int&);

    Layer(size_t id, PrintObject* object, coordf_t height, coordf_t print_z, coordf_t slice_z)
        : upper_layer(nullptr)
        , lower_layer(nullptr)
        , slicing_errors(false)
        , slice_z(slice_z)
        , print_z(print_z)
        , height(height)
        , m_id(id)
        , m_object(object)
    {}
    virtual ~Layer();

    // BBS: method to simplify support path
    void simplify_support_entity_collection(ExtrusionEntityCollection* entity_collection);
    void simplify_support_path(ExtrusionPath* path);
    void simplify_support_multi_path(ExtrusionMultiPath* multipath);
    void simplify_support_loop(ExtrusionLoop* loop);

private:
    // Sequential index of layer, 0-based, offsetted by number of raft layers.
    size_t          m_id;
    PrintObject*    m_object;
    LayerRegionPtrs m_regions;
};

enum SupportInnerType { stInnerNormal, stInnerTree };

class SupportLayer : public Layer
{
public:
    // Polygons covered by the supports: base, interface and contact areas.
    // Used to suppress retraction if moving for a support extrusion over these support_islands.
    ExPolygons support_islands;
    // Extrusion paths for the support base and for the support interface and contacts.
    ExtrusionEntityCollection support_fills;
    SupportInnerType          support_type = stInnerNormal;

    // for tree supports
    ExPolygons base_areas;

    // Is there any valid extrusion assigned to this LayerRegion?
    virtual bool has_extrusions() const { return !support_fills.empty(); }

    // Zero based index of an interface layer, used for alternating direction of interface / contact layers.
    size_t interface_id() const { return m_interface_id; }

    void simplify_support_extrusion_path() { this->simplify_support_entity_collection(&support_fills); }

protected:
    friend class PrintObject;
    friend class TreeSupport;

    // The constructor has been made public to be able to insert additional support layers for the skirt or a wipe tower
    // between the raft and the object first layer.
    SupportLayer(size_t id, size_t interface_id, PrintObject* object, coordf_t height, coordf_t print_z, coordf_t slice_z)
        : Layer(id, object, height, print_z, slice_z), m_interface_id(interface_id), support_type(stInnerNormal)
    {}
    virtual ~SupportLayer() = default;

    size_t m_interface_id;

    // for tree support
    ExPolygons roof_areas;
    ExPolygons roof_1st_layer; // the layer just below roof. When working with PolySupport, this layer should be printed with regular material
    ExPolygons floor_areas;
    ExPolygons roof_gap_areas; // the areas in the gap between support roof and overhang
    enum AreaType { BaseType = 0, RoofType = 1, FloorType = 2, Roof1stLayer = 3 };
    struct AreaGroup
    {
        ExPolygon* area;
        int        type;
        int        interface_id = 0;
        coordf_t   dist_to_top; // mm dist to top
        bool       need_infill     = false;
        bool       need_extra_wall = false;
        AreaGroup(ExPolygon* a, int t, coordf_t d) : area(a), type(t), dist_to_top(d) {}
    };
    std::vector<AreaGroup> area_groups;
};

template<typename LayerContainer> inline std::vector<float> zs_from_layers(const LayerContainer& layers)
{
    std::vector<float> zs;
    zs.reserve(layers.size());
    for (const Layer* l : layers)
        zs.emplace_back((float) l->slice_z);
    return zs;
}

extern BoundingBox get_extents(const LayerRegion& layer_region);
extern BoundingBox get_extents(const LayerRegionPtrs& layer_regions);
}

#endif
