#ifndef slic3r_VoronoiUtils_hpp_
#define slic3r_VoronoiUtils_hpp_

// [INTENT] Utility layer between raw boost::polygon Voronoi diagrams and the Arachne /
//   SkeletalTrapezoidation geometry pipeline.
//   Provides:
//     - SegmentCellRange<PT>  — iterator range over VD half-edges surrounding a segment cell.
//     - PointCellRange<PT>    — iterator range over VD half-edges surrounding a point cell.
//     - VoronoiUtils class    — static helpers for converting, querying, and discretizing VD.
//
// [COUPLING] Depends on boost::polygon VD layout and Arachne PolygonsSegmentIndex /
//   PolygonsPointIndex for source-segment identity.
// [MEMORY] All methods are stateless; cell ranges hold raw pointers into the VD (not owners).
// [HAZARD] Heavy use of boost::polygon enable_if SFINAE templates: adding a new SegmentIterator
//   type requires a matching explicit instantiation in VoronoiUtils.cpp or linker errors result.

#include <boost/polygon/polygon.hpp>
#include <iterator>
#include <limits>

#include "libslic3r/Geometry/Voronoi.hpp"
#include "libslic3r/Arachne/utils/PolygonsSegmentIndex.hpp"
#include "libslic3r/Arachne/utils/PolygonsPointIndex.hpp"
#include "libslic3r/Point.hpp"
#include "libslic3r/libslic3r.h"

using VD = Slic3r::Geometry::VoronoiDiagram;

namespace Slic3r::Geometry {

// [INTENT] Holds the first and last VD half-edges that enclose a trapezoid Voronoi cell
//   generated by an input line segment. edge_begin and edge_end bracket the usable region;
//   all edges in between (exclusive) can be iterated by following edge->next().
// [STATE] Raw non-owning pointers into VD; valid only while VD is live.
// Represent trapezoid Voronoi cell around segment.
template<typename PT> struct SegmentCellRange
{
    const PT             source_segment_start_point; // The start point of the source segment of this cell.
    const PT             source_segment_end_point;   // The end point of the source segment of this cell.
    const VD::edge_type* edge_begin = nullptr;       // The edge of the Voronoi diagram where the loop around the cell starts.
    const VD::edge_type* edge_end   = nullptr;       // The edge of the Voronoi diagram where the loop around the cell ends.

    SegmentCellRange() = delete;
    explicit SegmentCellRange(const PT& source_segment_start_point, const PT& source_segment_end_point)
        : source_segment_start_point(source_segment_start_point), source_segment_end_point(source_segment_end_point)
    {}

    bool is_valid() const { return edge_begin && edge_end && edge_begin != edge_end; }
};

// [INTENT] Holds the first and last VD half-edges that enclose a triangular Voronoi cell
//   generated by a single input point. The cell corresponds to a "corner" in the skeletal
//   trapezoidation graph.
// [STATE] Raw non-owning pointers into VD; valid only while VD is live.
// Represent trapezoid Voronoi cell around point.
template<typename PT> struct PointCellRange
{
    const PT             source_point;         // The source point of this cell.
    const VD::edge_type* edge_begin = nullptr; // The edge of the Voronoi diagram where the loop around the cell starts.
    const VD::edge_type* edge_end   = nullptr; // The edge of the Voronoi diagram where the loop around the cell ends.

    PointCellRange() = delete;
    explicit PointCellRange(const PT& source_point) : source_point(source_point) {}

    bool is_valid() const { return edge_begin && edge_end && edge_begin != edge_end; }
};

// [INTENT] Static utility class for working with boost::polygon VoronoiDiagrams in the
//   context of Arachne medial-axis / skeletal trapezoidation.
//
//   Key operations:
//     - to_point()               — convert VD vertex (double coords) to Vec2i64 via llround.
//     - is_finite() / is_in_range() — guard before integer conversion.
//     - get_source_segment/point/point_index() — recover the input geometry that generated a cell.
//     - discretize_parabola()    — parametric parabola to Points with transitioning-angle markers.
//     - compute_segment_cell_range() / compute_point_cell_range() — find edge_begin/edge_end.
//     - make_rotated_vertex()    — create a rotated copy of a VD vertex (used in debug/SVG).
//
// [COUPLING] All template methods are instantiated explicitly in VoronoiUtils.cpp for the
//   five iterator types used by Arachne. New iterator types require new explicit instantiations.
// [HAZARD] to_point() uses std::llround — UB if VD coords exceed INT64_MAX (H592).
class VoronoiUtils
{
public:
    // [INTENT] Round VD vertex double coordinates to integer space (coord_t = int64).
    // [HAZARD] H592: std::llround UB if coords exceed INT64_MAX; callers must call
    //   is_in_range<coord_t>() first for robustness.
    static Vec2i64 to_point(const VD::vertex_type* vertex);

    static Vec2i64 to_point(const VD::vertex_type& vertex);

    // [INTENT] Returns true iff vertex coordinates are finite (not infinity/NaN).
    static bool is_finite(const VD::vertex_type& vertex);

    // [INTENT] Create a new VD::vertex_type with coordinates rotated by 'angle' radians
    //   around the origin. Preserves incident_edge() and color() of the source vertex.
    //   Used in SVG debug rendering. Not inserted into the VD graph.
    static VD::vertex_type make_rotated_vertex(VD::vertex_type& vertex, double angle);

    // [INTENT] Return a reference to the input segment that generated the given VD cell.
    //   SFINAE-gated to segment concept types only.
    // [COUPLING] Uses cell.source_index() to index into [segment_begin, segment_end).
    template<typename SegmentIterator>
    static typename boost::polygon::enable_if<
        typename boost::polygon::gtl_if<typename boost::polygon::is_segment_concept<
            typename boost::polygon::geometry_concept<typename std::iterator_traits<SegmentIterator>::value_type>::type>::type>::type,
        typename std::iterator_traits<SegmentIterator>::reference>::type
    get_source_segment(const VD::cell_type& cell, SegmentIterator segment_begin, SegmentIterator segment_end);

    // [INTENT] Return the input point (start or end of segment) that generated the given
    //   point-site VD cell. Dispatches on source_category to choose line.a or line.b.
    template<typename SegmentIterator>
    static typename boost::polygon::enable_if<
        typename boost::polygon::gtl_if<typename boost::polygon::is_segment_concept<
            typename boost::polygon::geometry_concept<typename std::iterator_traits<SegmentIterator>::value_type>::type>::type>::type,
        typename boost::polygon::segment_point_type<typename std::iterator_traits<SegmentIterator>::value_type>::type>::type
    get_source_point(const VoronoiDiagram::cell_type& cell, SegmentIterator segment_begin, SegmentIterator segment_end);

    // [INTENT] Return the Arachne PolygonsPointIndex identifying which polygon/segment/point
    //   generated the given point-site VD cell.
    // [COUPLING] Requires SegmentIterator to be a PolygonsSegmentIndex-derived type.
    template<typename SegmentIterator>
    static typename boost::polygon::enable_if<
        typename boost::polygon::gtl_if<typename boost::polygon::is_segment_concept<
            typename boost::polygon::geometry_concept<typename std::iterator_traits<SegmentIterator>::value_type>::type>::type>::type,
        Arachne::PolygonsPointIndex>::type
    get_source_point_index(const VD::cell_type& cell, SegmentIterator segment_begin, SegmentIterator segment_end);

    /**
     * Discretize a parabola based on (approximate) step size.
     *
     * [INTENT] Convert a parabolic VD arc (focus = source_point, directrix = source_segment)
     *   into a polyline with approximately approximate_step_size spacing measured along the
     *   directrix. Inserts special "marking" points at transitioning_angle boundaries to
     *   indicate where the skeletal trapezoidation should switch between transition and normal
     *   bead strategies.
     *
     * [HAZARD] H593: if add_marking_start && add_marking_end && !add_apex, a warning is logged
     *   via BOOST_LOG_TRIVIAL but callers do not check for degraded output.
     *
     * Adapted from CuraEngine VoronoiUtils::discretizeParabola by Tim Kuipers @BagelOrb and @Ghostkeeper.
     *
     * @param approximate_step_size is measured parallel to the source_segment, not along the parabola.
     */
    template<typename Segment>
    static typename boost::polygon::enable_if<typename boost::polygon::gtl_if<typename boost::polygon::is_segment_concept<
                                                  typename boost::polygon::geometry_concept<Segment>::type>::type>::type,
                                              Points>::type
    discretize_parabola(const Point&   source_point,
                        const Segment& source_segment,
                        const Point&   start,
                        const Point&   end,
                        coord_t        approximate_step_size,
                        float          transitioning_angle);

    /**
     * Compute the range of line segments that surround a cell of the skeletal
     * graph that belongs to a line segment of the medial axis.
     *
     * [INTENT] Find edge_begin and edge_end pointers for a trapezoid VD cell so that callers
     *   can iterate the relevant VD half-edges via edge->next(). Identifies the two edges whose
     *   v0 == to_i64(segment.to) and v1 == to_i64(segment.from) as begin/end boundaries.
     *
     * [HAZARD] H591: the do-while loop uses comma operator to advance edge = edge->next() even
     *   when a `continue` is hit for infinite edges — correct, but fragile to refactor.
     *
     * This should only be used on cells that belong to a central line segment
     * of the skeletal graph, e.g. trapezoid cells, not triangular cells.
     *
     * The resulting line segments is just the first and the last segment. They
     * are linked to the neighboring segments, so you can iterate over the
     * segments until you reach the last segment.
     *
     * Adapted from CuraEngine VoronoiUtils::computeSegmentCellRange by Tim Kuipers @BagelOrb,
     * Jaime van Kessel @nallath, Remco Burema @rburema and @Ghostkeeper.
     *
     * @param cell The cell to compute the range of line segments for.
     * @param segment_begin Begin iterator for all edges of the input Polygons.
     * @param segment_end End iterator for all edges of the input Polygons.
     * @return Range of line segments that surround the cell.
     */
    template<typename SegmentIterator>
    static typename boost::polygon::enable_if<
        typename boost::polygon::gtl_if<typename boost::polygon::is_segment_concept<
            typename boost::polygon::geometry_concept<typename std::iterator_traits<SegmentIterator>::value_type>::type>::type>::type,
        Geometry::SegmentCellRange<
            typename boost::polygon::segment_point_type<typename std::iterator_traits<SegmentIterator>::value_type>::type>>::type
    compute_segment_cell_range(const VD::cell_type& cell, SegmentIterator segment_begin, SegmentIterator segment_end);

    /**
     * Compute the range of line segments that surround a cell of the skeletal
     * graph that belongs to a point on the medial axis.
     *
     * [INTENT] Find edge_begin and edge_end pointers for a triangular (point-site) VD cell.
     *   Filters out cells that are geometrically outside the input polygon using
     *   is_point_inside_polygon_corner(). Returns an invalid range if the cell is outside.
     *
     * This should only be used on cells that belong to a corner in the skeletal
     * graph, e.g. triangular cells, not trapezoid cells.
     *
     * The resulting line segments is just the first and the last segment. They
     * are linked to the neighboring segments, so you can iterate over the
     * segments until you reach the last segment.
     *
     * Adapted from CuraEngine VoronoiUtils::computePointCellRange by Tim Kuipers @BagelOrb
     * Jaime van Kessel @nallath, Remco Burema @rburema and @Ghostkeeper.
     *
     * @param cell The cell to compute the range of line segments for.
     * @param segment_begin Begin iterator for all edges of the input Polygons.
     * @param segment_end End iterator for all edges of the input Polygons.
     * @return Range of line segments that surround the cell.
     */
    template<typename SegmentIterator>
    static typename boost::polygon::enable_if<
        typename boost::polygon::gtl_if<typename boost::polygon::is_segment_concept<
            typename boost::polygon::geometry_concept<typename std::iterator_traits<SegmentIterator>::value_type>::type>::type>::type,
        Geometry::PointCellRange<
            typename boost::polygon::segment_point_type<typename std::iterator_traits<SegmentIterator>::value_type>::type>>::type
    compute_point_cell_range(const VD::cell_type& cell, SegmentIterator segment_begin, SegmentIterator segment_end);

    // [INTENT] Return true iff the double value fits in the integer range of type T.
    //   Used as a guard before to_point() conversion to prevent UB from llround overflow.
    template<typename T> static bool is_in_range(double value)
    {
        return double(std::numeric_limits<T>::lowest()) <= value && value <= double(std::numeric_limits<T>::max());
    }

    // [INTENT] Return true iff the VD vertex is finite and both coordinates fit in T.
    template<typename T> static bool is_in_range(const VD::vertex_type& vertex)
    {
        return VoronoiUtils::is_finite(vertex) && is_in_range<T>(vertex.x()) && is_in_range<T>(vertex.y());
    }

    // [INTENT] Return true iff both endpoints of the VD edge are finite and fit in T.
    //   Returns false for infinite (unbounded) edges.
    template<typename T> static bool is_in_range(const VD::edge_type& edge)
    {
        if (edge.vertex0() == nullptr || edge.vertex1() == nullptr)
            return false;

        return is_in_range<T>(*edge.vertex0()) && is_in_range<T>(*edge.vertex1());
    }
};

} // namespace Slic3r::Geometry

#endif // slic3r_VoronoiUtils_hpp_
