#ifndef slic3r_GLGizmoSimplify_hpp_
#define slic3r_GLGizmoSimplify_hpp_

// Include GLGizmoBase.hpp before I18N.hpp as it includes some libigl code,
// which overrides our localization "L" macro.
#include "GLGizmoBase.hpp"
#include "slic3r/GUI/3DScene.hpp"
#include "admesh/stl.h" // indexed_triangle_set
#include <mutex>
#include <thread>

namespace Slic3r {
class ModelVolume;
class Model;

namespace GUI {
class NotificationManager; // for simplify suggestion

class GLGizmoSimplify : public GLGizmoBase
{
public:
    // [INTENT] Wraps the simplifier preview so users can inspect decimations before committing, while keeping the GL model responsive.
    GLGizmoSimplify(GLCanvas3D& parent, const std::string& icon_filename, unsigned int sprite_id);
    virtual ~GLGizmoSimplify();
    bool on_esc_key_down();
    // [EVENT] Surface a notification back to the manager when background suggestions are generated by the simplification routine.
    static void add_simplify_suggestion_notification(const std::vector<size_t>&       object_ids,
                                                     const std::vector<ModelObject*>& objects,
                                                     NotificationManager&             manager);

protected:
    virtual std::string on_get_name() const override;
    virtual void        on_render_input_window(float x, float y, float bottom_limit) override;
    virtual bool        on_is_activable() const override;
    virtual bool        on_is_selectable() const override { return false; }
    virtual void        on_set_state() override;

    // must implement
    virtual bool on_init() override { return true; };
    virtual void on_render() override;

    CommonGizmosDataID on_get_requirements() const override;

private:
    // [EVENT][THREAD] Kicks off the simplification job while keeping the UI responsive; publishes progress via `m_state`.
    void apply_simplify();
    void close();

    // [EVENT] Drives the asynchronous state machine that keeps the simplifier progress aligned with UI controls.
    void process();
    // [THREAD] Signals the worker to cancel asynchronously during tear-down or config switches.
    void stop_worker_thread_request();
    // [EVENT][THREAD] Called from the UI thread when the worker completes so the preview swap happens safely.
    void worker_finished();

    void create_gui_cfg();
    // [EVENT][OPENGL] Asks GLCanvas3D for a redraw so the simplified mesh or progress overlay stays in sync with the latest state.
    void request_rerender(bool force = false);
    void init_model(const indexed_triangle_set& its);

    void set_center_position();

    struct Configuration
    {
        bool     use_count      = false;
        float    decimate_ratio = 50.f; // in percent
        uint32_t wanted_count   = 0;    // initialize by percents
        float    max_error      = 1.;   // maximal quadric error

        void fix_count_by_ratio(size_t triangle_count);
        bool operator==(const Configuration& rhs)
        {
            return (use_count == rhs.use_count && decimate_ratio == rhs.decimate_ratio && wanted_count == rhs.wanted_count &&
                    max_error == rhs.max_error);
        }
        bool operator!=(const Configuration& rhs) { return !(*this == rhs); }
    };

    // [STATE] Preserves the user's simplification wishlist so the worker can resume exactly the same criteria after a rerender.
    Configuration m_configuration;

    // [STATE] When true, camera/walkaround logic repositions the mesh before showing the simplifier UI.
    bool m_move_to_center; // opening gizmo

    // [STATE] Points at the live ModelVolume being decimated so the GLSimplify job can query vertex buffers safely.
    const ModelVolume* m_volume; // keep pointer to actual working volume

    // [STATE][OPENGL] Wireframe toggle and cached GLModel used for overlay rendering.
    bool    m_show_wireframe;
    GLModel m_glmodel;
    size_t  m_triangle_count; // triangle count of the model currently shown

    // [STATE][THREAD] Timestamp of the last rerender request so the UI only redraws after a short cooldown on the main thread.
    int64_t m_last_rerender_timestamp = std::numeric_limits<int64_t>::min();

    // [STATE][THREAD] State shared between the UI thread and worker thread; all access must hold `m_state_mutex`.
    struct State
    {
        enum Status { idle, running, cancelling };

        Status                                status   = idle;
        int                                   progress = 0; // percent of done work
        Configuration                         config;       // Configuration we started with.
        const ModelVolume*                    mv = nullptr;
        std::unique_ptr<indexed_triangle_set> result;
    };

    // [THREAD] Worker thread that runs the simplification algorithm so the UI thread stays responsive.
    std::thread m_worker;
    // [THREAD] Mutex guarding `m_state`.
    std::mutex m_state_mutex;
    // [STATE][THREAD] Reflects the current worker progress and result; touched by both threads under the mutex.
    State m_state;

    // This configs holds GUI layout size given by translated texts.
    // etc. When language changes, GUI is recreated and this class constructed again,
    // so the change takes effect. (info by GLGizmoFdmSupports.hpp)
    // [STATE][UNITY] GUI layout sizes tied to translated labels; Unity port needs to rebuild these when the language changes.
    struct GuiCfg
    {
        int top_left_width    = 100;
        int bottom_left_width = 100;
        int input_width       = 100;
        int window_offset_x   = 100;
        int window_offset_y   = 100;
        int window_padding    = 0;

        // trunc model name when longer
        size_t max_char_in_name = 30;

        // to prevent freezing when move in gui
        // delay before process in [ms]
        std::chrono::duration<long int, std::milli> prcess_delay = std::chrono::milliseconds(250);
    };
    // [STATE] Cached window layout derived from the current translation bundle.
    std::optional<GuiCfg> m_gui_cfg;

    // translations used for calc window size
    // [UNITY] Unity should hydrate these strings from a localized `LocalizationTable` rather than raw `L()` macros.
    const std::string tr_mesh_name;
    const std::string tr_triangles;
    const std::string tr_detail_level;
    const std::string tr_decimate_ratio;

    // cancel exception
    class SimplifyCanceledException : public std::exception
    {
    public:
        // [PORTING_HAZARD:P3] Cancellation must propagate back to Unity’s async job system on the main thread; dropping here would leave
        // meshes in an intermediate state.
        const char* what() const throw() { return L("Model simplification has been canceled"); }
    };
};

} // namespace GUI
} // namespace Slic3r

#endif // slic3r_GLGizmoSimplify_hpp_
